version: "2"
services:
  #elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - service-network
  #kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - service-network
  #redis
  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - service-network
    volumes:
      - redis-data:/data
  #lol
  # lol:
  #   image: lol:1.0.0
  #   container_name: lol
  #   command: ["npm", "start"]
  #   hostname: lol
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - service-network
  #   depends_on:
  #     - elasticsearch
  #     - redis
volumes:
  redis-data:
    driver: local
  esdata:
    driver: local
networks:
  service-network:
